---
name: ğŸ—¼ Lighthouse
on: [push]

permissions: {}

jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ‘ Checkout
        uses: actions/checkout@v4

      - name: ğŸ¢ Checkout Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0

      - name: ğŸ“¥ Install Dependecies
        run: |
          npm ci
          npm install @rollup/rollup-linux-x64-gnu --save-optional
          npm install -g @lhci/cli@0.14.x

      - name: ğŸ—ï¸ Build App
        run: npm run build

      - name: ğŸ“Š Run Lighthouse
        run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
